openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
  description: API for managing users
  contact: {}
paths:
  /api/v1/users:
    get:
      operationId: get~users.get_user
      summary: Get User
      tags:
        - users
      parameters:
        - name: x-telegram-user-id
          in: header
          required: true
          schema:
            type: string
          description: ID of the Telegram user
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
        default:
          description: OK
tags:
  - name: users
servers:
  - url: http://127.0.0.1:8000
    description: Local server
    variables: {}
security: []
